### ISSUE TITLE
update-vm.sh must be chmod 7xx when running from OS X

### ISSUE THREAD

**Issue by damphyr** [Zuehlke/linux-developer-vm#8]
/vagrant is mounted with the permissions of the host.

We could do this with a method in the vagrant file or just put a comment in it

**Comment by tknerr** [comment]
Actually I already made it executable here:
https://github.com/Zuehlke/linux-developer-vm/commit/1fa6c70b10d69994bf73dce28052d916b6d56cf6

If that didn't work, it might be an issue with either Github or MSYS as
mentioned here:
http://stackoverflow.com/questions/9027584/how-to-change-the-file-mode-on-github

So it might be worth a try to revert it and make it executable again from
an OS which handles chmod properly
Am 25.05.2016 12:51 nachm. schrieb "Vassilis Rizopoulos" <
notifications@github.com>:

**Comment by tknerr** [comment]
I will keep this open until I have my MacBook to test it ;-)

**Comment by tknerr** [comment]
Looks all fine on macOS. After cloning the repo the file mode is 755:

![image](https://cloud.githubusercontent.com/assets/365744/25538680/f1595a20-2c43-11e7-8ecd-2ddeef156757.png)

(was fixed earlier via 1fa6c70b10d69994bf73dce28052d916b6d56cf6)
